version: '3.8'

services:
  mysql:
    image: mysql:8.4.1
    container_name: mysql-simpledb
    ports:
      - "3306:3306"
    volumes:
      - ./db/volumes/var/lib/mysql:/var/lib/mysql
      - ./db/volumes/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: lldj123414
    restart: always